### ISSUE TITLE
missing DL::Importable

### ISSUE THREAD

**Issue by Dubl** [bleything/midiator#1]
Hi. I cant seem to find any active forum on this anywhere.. or an appropriate one anyway. I installed midiator , running ruby 1.9.1 on windows xp. its telling me i have an unititialized constant DL::Importable. I have no idea why it wouldnt be finding this, but ..aregggh

fyi im making some object-oriented melodies :)

**Comment by bleything** [comment]
Ruby 1.9 changed the DL internals around, and as a consequence MIDIator is not supported under 1.9.

The path forward seems to be to port to FFI, but as I A) don't use Windows and B) am still using 1.8, it's hard for me to work on that.  Patches, as always, are welcome :)

**Comment by elgiano** [comment]
I made some patches to achieve compatibility with 1.8 and 1.9, which i've loaded on my repository. Anyway, i'm on linux and i've only tested alsa.rb ( so far i've only tested the play method ), but i think everything should work.

**Comment by Dubl** [comment]
awesome. works on windows (play)...   now i can move into the world of 1.9...
